---
 déploiement:
   les tâches:
     - export DEPLOYPATH = / home / utilisateur / public_html /
     - / bin / cp index.html $ DEPLOYPATH
     - / bin / cp style.css $ DEPLOYPATH 
     - / bin / cp calendar.js $DEPLOYPATH